const dayNames = ['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const weeklyFormats = [
  {name:'Escuta sem texto + com transcrição',resource:'British Council — B1 Listening',task:'Ouça uma vez sem legenda para captar a ideia principal. Na segunda escuta, abra a transcrição em inglês e marque até três trechos que bloquearam o sentido.',output:'Resuma o áudio em duas frases e salve duas expressões úteis.'},
  {name:'Vídeo de interesse + shadowing',resource:'Vídeo em inglês pré-selecionado no seu barril',task:'Assista a um trecho curto. Pause para explicar o que está acontecendo; depois repita uma frase imitando ritmo e entonação.',output:'Grave 30–60 segundos explicando a atividade ou o tema.'},
  {name:'Gramática em contexto',resource:'Frase salva + Cambridge Dictionary / English Grammar in Use',task:'Observe o padrão gramatical da semana dentro de uma frase real. Consulte uma explicação curta e crie exemplos verdadeiros sobre sua vida.',output:'Escreva três frases e reformule-as depois de receber uma correção.'},
  {name:'Entrevista + resposta espontânea',resource:'BBC Learning English — 6 Minute English ou áudio equivalente',task:'Ouça um trecho curto sem texto. Imagine que participa da conversa: responda a uma pergunta do episódio e faça uma pergunta de volta.',output:'Anote uma pergunta natural e responda sem ler um roteiro.'},
  {name:'Tecnologia explicada em voz alta',resource:'Tutorial de programação ou Minecraft com áudio em inglês',task:'Ouça primeiro sem legendas; use legendas em inglês na segunda passagem. Repare em uma instrução, explicação ou sequência de causa e efeito.',output:'Explique o processo ou a solução em 45 segundos.'},
  {name:'Leitura, escrita e correção',resource:'Documentação, postagem curta ou texto do barril',task:'Leia pelo sentido, escolha uma ideia e escreva uma resposta curta. Peça à IA que corrija até dois padrões e explique por que, sem reescrever sua voz.',output:'Guarde o original, a revisão e um padrão para observar.'},
  {name:'Revisão e preparação',resource:'Seus áudios, frases e notas da semana',task:'Reouça o primeiro áudio sem texto. Tente recuperar frases sem olhar e escolha o conteúdo principal da próxima semana.',output:'Registre o que ficou mais fácil e prepare até cinco itens no barril.'}
];
const vocabSets = {
  daily:['wake up','get dressed','make the bed','take a shower','brush my teeth','have breakfast','make coffee','leave home','commute','get to work','take a break','have lunch','run an errand','come back','cook dinner','do the dishes','do the laundry','tidy up','take out the trash','go to bed','weekday','weekend','morning','afternoon','evening','schedule','routine','habit','appointment','reminder','alarm','suburb','neighborhood','crosswalk','sidewalk','traffic','bus stop','commute time','crowded','quiet','convenient','nearby','on time','late','early','usually','often','rarely','sometimes','first','then','afterwards','before','while','until','because','although','manage to','need to','have to','would rather','get ready','pick up','drop off','look for','run out of','spend time','in a hurry','at the moment','every other day','once a week','take my time','make a plan'],
  home:['apartment','house','roommate','landlord','tenant','rent','lease','deposit','utility bill','electricity','water bill','internet connection','furniture','bookshelf','desk','drawer','shelf','closet','ceiling','floor','wall','window','curtain','lamp','outlet','extension cord','key','lock','doorbell','intercom','kitchen','bathroom','laundry room','living room','bedroom','storage','move in','move out','unpack','assemble','repair','replace','fix','leak','broken','messy','comfortable','spacious','tiny','furnished','unfurnished','available','shared','quiet hours','household chores','vacuum cleaner','washing machine','dishwasher','oven','stove','fridge','freezer','microwave','sink','tap','towel','bedsheet','pillowcase','clean up','put away','throw away','sort out','run smoothly','be responsible for','take turns','keep something tidy'],
  food:['ingredient','recipe','meal','snack','side dish','main course','dessert','appetizer','portion','serving','leftovers','grocery shopping','shopping list','basket','checkout','aisle','receipt','price tag','discount','ripe','fresh','frozen','canned','spicy','mild','sweet','sour','bitter','salty','crispy','soft','tender','overcooked','undercooked','chop','slice','peel','stir','boil','fry','bake','grill','roast','season','taste','smell','order','book a table','menu','waiter','bill','tip','takeaway','delivery','dine in','allergy','vegetarian','vegan','gluten-free','dairy-free','thirsty','hungry','full','recommend','Could I have…?','Would you mind…?','It tastes like…','run out of','pick up groceries','eat out','home-cooked','comfort food'],
  social:['introduce yourself','get together','catch up','hang out','make friends','keep in touch','get along','have in common','small talk','conversation','topic','opinion','point of view','agree','disagree','interrupt','take turns','follow up','bring up','change the subject','by the way','actually','I mean','you know','to be honest','fair enough','that makes sense','I see what you mean','I’m not sure about that','what do you think?','How do you know them?','Where are you from?','What have you been up to?','meetup','gathering','host','guest','invitation','crowd','stranger','acquaintance','close friend','colleague','neighbor','polite','friendly','awkward','comfortable','confident','nervous','curious','supportive','reliable','sense of humor','share a story','ask a question','listen carefully','show interest','make a suggestion','give someone a hand','get together with','be into','be keen on','It depends','That reminds me','Speaking of…','Anyway…','I’d love to','Maybe next time','Sounds good','I couldn’t agree more','I’m afraid I have to go'],
  directions:['turn left','turn right','go straight','cross the street','at the corner','traffic lights','intersection','roundabout','crosswalk','pedestrian','block','avenue','lane','main road','side street','downtown','city center','neighborhood','landmark','entrance','exit','platform','track','ticket machine','fare','transfer','route','stop','station','terminal','departure','arrival','schedule','delay','cancelled','crowded','accessible','nearby','opposite','across from','next to','between','behind','in front of','on the left','on the right','get on','get off','set off','pick someone up','drop someone off','miss the bus','catch a train','traffic jam','rush hour','one-way street','public transport','commuter','pedestrian zone','parking lot','gas station','map','directions','shortcut','detour','How do I get to…?','Is it within walking distance?','Which stop should I get off at?','It’s about ten minutes away','Could you show me on the map?','as soon as possible','on the way','take the next exit'],
  health:['feel under the weather','have a cold','have a cough','sore throat','runny nose','blocked nose','headache','stomachache','backache','toothache','fever','rash','swelling','bruise','cut','pain','ache','symptom','appointment','checkup','clinic','pharmacy','prescription','medicine','painkiller','dosage','side effect','allergy','emergency','receptionist','doctor','nurse','dentist','patient','health insurance','medical history','recover','get better','get worse','rest','stay hydrated','take medicine','make an appointment','cancel an appointment','explain how you feel','breathe','cough','sneeze','dizzy','tired','exhausted','stressed','anxious','relieved','healthy','unwell','sensitive','severe','mild','How long have you had it?','It hurts when…','I’ve been feeling…','Could you take a look?','Is there anything I should avoid?','book an appointment','look after yourself','get some sleep','take a day off','on an empty stomach','twice a day'],
  work:['coworker','colleague','manager','team lead','client','customer','meeting','agenda','minutes','deadline','task','priority','project','progress','update','feedback','workload','shift','remote work','office','workspace','break room','promotion','salary','benefit','contract','application','resume','cover letter','interview','experience','skill','qualification','strength','weakness','responsibility','department','company','industry','hire','apply for','follow up','hand in','set up','work on','deal with','figure out','carry out','put off','bring forward','meet a deadline','miss a deadline','make a decision','solve a problem','come up with an idea','take responsibility','keep someone posted','work independently','work as a team','I’m in charge of…','I’m responsible for…','Could you clarify…?','Let’s go over…','I’ll get back to you','as far as I know','from my perspective','on the same page','That works for me','I have a question about…','check in with','wrap up','be available','annual leave'],
  minecraft:['world','realm','server','seed','spawn point','biome','village','stronghold','nether portal','end portal','overworld','Nether','the End','survival mode','creative mode','hardcore mode','multiplayer','single-player','player','mob','hostile mob','passive mob','boss','villager','trader','inventory','hotbar','crafting table','furnace','blast furnace','smoker','anvil','chest','barrel','hopper','redstone dust','repeater','comparator','lever','button','pressure plate','piston','sticky piston','observer','dispenser','dropper','redstone circuit','signal','power','activate','deactivate','place a block','break a block','mine for','dig down','build a shelter','gather resources','craft an item','smelt ore','breed animals','grow crops','light up an area','spawn','despawn','drop loot','take damage','heal','respawn','fall damage','durability','enchantment','potion effect','recipe','recipe book','coordinates','chunk','tick','lag','update','patch','bug','mod','resource pack','behavior pack','command','redstone contraption'],
  learning:['improve','make progress','struggle with','find it difficult','get used to','be familiar with','figure out','look up','review','revise','practice','rehearse','memorize','remember','forget','recognize','understand','misunderstand','pronounce','spelling','vocabulary','grammar','sentence','phrase','expression','meaning','context','example','mistake','correction','feedback','fluency','accuracy','confidence','skill','strength','weakness','goal','plan','routine','progress','challenge','strategy','resource','transcript','subtitle','caption','speaker','accent','speed','background noise','connected speech','stress','intonation','syllable','linking','shadowing','chorusing','sentence mining','flashcard','spaced repetition','recall','summarize','retell','paraphrase','ask for clarification','Could you repeat that?','What does … mean?','How do you spell that?','I didn’t catch that','Let me put it another way','The main point is…','As far as I understand…','I’m working on…','I’ve noticed that…','I used to…','I’m getting better at…'],
  technology:['device','settings','account','password','username','privacy','notification','screen time','browser','search engine','website','webpage','link','download','upload','file','folder','backup','storage','cloud','Wi-Fi','connection','network','router','keyboard','shortcut','tab','window','update','version','feature','tool','app','software','hardware','operating system','bug','error','crash','glitch','issue','fix','troubleshoot','restart','install','uninstall','sign in','log in','log out','set up','turn on','turn off','scroll down','click on','tap on','type in','fill in','save changes','back up','reset a password','enable','disable','sync','share','permission','access','user-friendly','reliable','secure','compatible','My screen is frozen','I can’t connect to…','Where can I find…?','It keeps asking me to…','I’ve tried restarting it','step by step'],
  programming:['codebase','source code','programming language','framework','library','dependency','package','repository','branch','commit','pull request','issue','bug report','feature request','user interface','backend','frontend','database','server','client','API','request','response','endpoint','input','output','variable','function','parameter','argument','return value','condition','loop','array','object','class','method','property','module','component','script','terminal','command line','editor','debugger','test','unit test','build','deploy','release','version control','documentation','syntax','runtime','error message','stack trace','log','reproduce a bug','fix a bug','write code','run a script','test a feature','review a change','merge a branch','push a commit','pull the latest changes','set up a project','install a package','pass in a value','call a function','return an error','It looks like…','The issue happens when…','I expected … but got…','Could you take a look at…?','I’ve narrowed it down to…','Let me walk you through it'],
  opinions:['opinion','viewpoint','perspective','argument','evidence','example','reason','benefit','drawback','advantage','disadvantage','trade-off','impact','consequence','claim','assumption','fact','bias','reliable source','research','survey','trend','issue','concern','solution','approach','option','alternative','choice','decision','convince','persuade','agree','disagree','object','support','challenge','consider','compare','evaluate','suggest','recommend','argue','claim','point out','bring up','look at','depend on','lead to','result in','make a difference','have an effect on','from my point of view','as far as I’m concerned','I see your point, but…','One reason is…','For instance…','On the other hand…','That said…','To some extent…','It seems to me that…','I’m not convinced that…','The main drawback is…','There’s no simple answer','It’s worth considering…','I’d rather…','I tend to think…','What matters most is…','in the long run','in practice','in theory'],
  stories:['experience','memory','childhood','background','event','situation','beginning','middle','ending','turning point','at first','eventually','suddenly','meanwhile','in the end','once','while','as soon as','by the time','afterward','beforehand','during','unfortunately','luckily','surprisingly','apparently','probably','definitely','realize','notice','recognize','remember','forget','decide','manage','fail','succeed','expect','hope','wonder','promise','explain','describe','mention','admit','suggest','interrupt','I had never… before','I was about to…','It turned out that…','What happened was…','The reason I… was…','I didn’t realize that…','Looking back…','As soon as I got there…','While I was waiting…','By the time we arrived…','I ended up…','I was supposed to…','It was the first time…','That’s when I realized…','One thing I remember is…','I couldn’t believe it','make up your mind','take place','come across','run into someone','on my way back','for a while','out of nowhere','from then on','the whole time','to my surprise','long story short','personal experience','share a story'],
  plans:['goal','milestone','timeline','schedule','routine','commitment','reminder','progress','set a goal','make a plan','stick to a plan','fall behind','catch up','keep track of','check off','complete','continue','pause','adjust','review','reflect','measure','estimate','deadline','long-term','short-term','realistic','achievable','consistent','regular','flexible','focused','distraction','motivation','effort','habit','practice session','study time','free time','weekly','daily','monthly','eventually','by next week','in a few months','from now on','once a day','twice a week','at least','no more than','as soon as','make time for','put aside','work toward','break down','keep going','take a break','start over','pick up where I left off','I’m aiming to…','My next step is…','I’ve managed to…','I still need to…','I’m planning to…','What worked well was…','I could improve by…','little by little','one step at a time','on a regular basis','make steady progress','stay on track','look back on','set aside time','as planned']
};
const weeks = [
  {theme:'Um dia típico',subtitle:'Construa frases para narrar sua rotina de verdade.',grammar:'Present simple × present continuous',grammarNote:'Compare hábitos com ações acontecendo agora: “I usually study at night” × “I’m studying right now.”',vocab:'daily',content:'British Council B1: “A day in the life”; descreva sua rotina real e ouça um áudio curto sobre hábitos.',resources:[['British Council — B1 listening','https://learnenglish.britishcouncil.org/skills/listening/b1-listening'],['Cambridge Dictionary','https://dictionary.cambridge.org/']],activities:['Ouça um áudio B1 sobre rotina. Sem texto, identifique três partes do dia e a ideia geral.','Narre uma rotina familiar em inglês. Faça shadowing de duas frases com horários ou frequência.','Compare “I usually…” com “I’m …ing now”. Escreva três frases sobre hábitos e o que está fazendo hoje.','Ouça novamente; pause após uma pergunta e responda como se conhecesse a pessoa entrevistada.','Explique seu começo de dia em 45 segundos. Regrave uma vez tentando conectar as frases.','Escreva uma mensagem para um amigo descrevendo seu dia. Peça à IA correção de até dois padrões.','Reouça o áudio de segunda sem texto. Escolha o áudio da próxima semana e deixe-o salvo.']},
  {theme:'Casa e tarefas',subtitle:'Fale sobre onde você mora e como cuida do espaço.',grammar:'There is / there are + quantificadores',grammarNote:'Descreva espaços com “There’s a desk”, “There are two shelves” e “There isn’t much room.”',vocab:'home',content:'História de nível B1 sobre moradia ou organização; tour de casa simples em inglês com legenda inglesa.',resources:[['British Council — Audio series','https://learnenglish.britishcouncil.org/free-resources/general/audio-series'],['YouGlish','https://youglish.com/english']],activities:['Ouça uma conversa curta sobre casa. Descubra quem mora onde e qual é o problema.','Assista a um pequeno room tour em inglês. Pause e descreva três objetos ao redor.','Pratique there is/are e quantificadores usando o seu quarto. Grave uma descrição curta.','Ouça um trecho novamente e responda: “What would you change about your place?”','Explique um conserto ou uma tarefa doméstica passo a passo. Repita as instruções em shadowing.','Escreva uma mensagem para um proprietário relatando um problema simples. Peça correção.','Revise cinco expressões e reouça o room tour sem legenda. Prepare o tema comida.']},
  {theme:'Comida e pedidos',subtitle:'Peça, recomende e descreva comida com naturalidade.',grammar:'Countable / uncountable + some, any, much, many',grammarNote:'Use “some rice”, “many ingredients”, “How much water?” e “Are there any…?” em pedidos e receitas.',vocab:'food',content:'Vídeo curto de receita ou episódio sobre alimentação; descreva sabores e preferências.',resources:[['BBC Learning English','https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'],['Cambridge Dictionary','https://dictionary.cambridge.org/']],activities:['Ouça um diálogo de restaurante. Na primeira vez, descubra o pedido e a preferência alimentar.','Siga uma receita curta em inglês. Repita três verbos de ação junto ao falante.','Crie perguntas com how much/how many sobre ingredientes da sua refeição.','Faça roleplay: peça uma refeição e pergunte sobre um ingrediente.','Descreva como preparar um prato em 45 segundos usando first, then e finally.','Escreva uma recomendação de restaurante ou receita em três frases e revise com IA.','Reouça a receita e tente lembrar os ingredientes sem consultar. Prepare uma situação social.']},
  {theme:'Conhecer pessoas',subtitle:'Inicie conversas e mantenha a troca fluindo.',grammar:'Perguntas e respostas curtas no presente e no passado',grammarNote:'Pratique inversão auxiliar-sujeito: “Do you…?”, “Have you…?” e “Did you…?”; responda e devolva uma pergunta.',vocab:'social',content:'Entrevista leve ou conversa entre pessoas; observe perguntas de acompanhamento e sinais de interesse.',resources:[['British Council — B1 listening','https://learnenglish.britishcouncil.org/skills/listening/b1-listening'],['YouGlish','https://youglish.com/english']],activities:['Ouça uma apresentação e identifique como as pessoas se conhecem. Note duas perguntas naturais.','Faça shadowing de perguntas curtas e entonação. Depois apresente-se em 30 segundos.','Transforme três afirmações sobre você em perguntas abertas para outra pessoa.','Simule uma conversa em um meetup: apresente-se, faça duas perguntas e acompanhe uma resposta.','Ouça a entrevista e pause para responder antes da pessoa entrevistada.','Peça à IA um roleplay de conversa casual; solicite feedback apenas no final.','Revise as perguntas sem olhar e grave uma apresentação um pouco mais espontânea.']},
  {theme:'Cidade e deslocamentos',subtitle:'Peça ajuda, entenda direções e converse durante o caminho.',grammar:'Preposições de lugar e imperativos',grammarNote:'Combine in/on/at, across from, next to e imperativos: “Go straight”, “Turn left at the lights.”',vocab:'directions',content:'Áudio de direções em uma cidade; mapa ou vídeo curto de percurso com fala clara.',resources:[['British Council — B1 listening','https://learnenglish.britishcouncil.org/skills/listening/b1-listening'],['Cambridge Dictionary','https://dictionary.cambridge.org/']],activities:['Ouça instruções de caminho sem texto e desenhe mentalmente o percurso.','Use um mapa e explique como chegar de um ponto conhecido a outro.','Pratique preposições descrevendo objetos e lugares próximos.','Roleplay: peça direções, confirme o ponto de referência e pergunte onde descer.','Ouça um anúncio ou conversa sobre atraso. Anote onde e quando acontece.','Escreva direções para um visitante. Peça à IA para apontar ambiguidades.','Repita o percurso sem olhar para o mapa e escolha conteúdo de saúde.']},
  {theme:'Saúde e bem-estar',subtitle:'Explique sintomas e entenda orientações simples.',grammar:'Present perfect para duração + should / have to',grammarNote:'Use “I’ve had a cough for two days” e “You should rest”; compare conselhos com obrigação.',vocab:'health',content:'Conversa de consulta ou áudio B1 de hábitos saudáveis; aprenda a descrever duração e intensidade.',resources:[['British Council — Audio series','https://learnenglish.britishcouncil.org/free-resources/general/audio-series'],['Cambridge Dictionary','https://dictionary.cambridge.org/']],activities:['Ouça uma conversa de consulta e identifique sintomas e recomendação.','Repita frases para explicar duração e intensidade. Treine ritmo sem tentar imitar sotaque perfeitamente.','Crie exemplos com for/since e should/have to usando situações fictícias simples.','Faça roleplay curto: explique como se sente e peça para repetir uma orientação.','Reouça um trecho sem legenda; liste palavras de sintoma reconhecidas pelo som.','Escreva uma mensagem curta pedindo para remarcar um compromisso por estar doente.','Recupere as expressões da semana e reescute o primeiro diálogo.']},
  {theme:'Trabalho e colaboração',subtitle:'Contribua em conversas profissionais e explique prioridades.',grammar:'Modais para pedidos, possibilidade e conselho',grammarNote:'Compare “Could you…?”, “We might…” e “You should…” para soar claro e educado.',vocab:'work',content:'Entrevista ou reunião curta sobre equipe; tutorial técnico falado ligado à programação.',resources:[['BBC Learning English','https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'],['English Grammar in Use','https://www.cambridge.org/gb/cambridgeenglish/catalog/grammar-vocabulary-and-pronunciation/english-grammar-use-5th-edition']],activities:['Ouça uma conversa de equipe e identifique tarefa, prazo e responsável.','Explique seu projeto atual como uma atualização de reunião. Faça shadowing de uma frase útil.','Transforme instruções diretas em pedidos com could/would. Crie três exemplos.','Simule uma reunião: dê uma atualização e peça esclarecimento sobre uma prioridade.','Ouça um tutorial de programação. Resuma problema e solução em voz alta.','Escreva uma mensagem profissional curta solicitando informação e peça feedback.','Reouça o áudio e pratique “Could you clarify…?” sem ler. Escolha um tópico Minecraft.']},
  {theme:'Minecraft: explicar o jogo',subtitle:'Transforme seu interesse em fala detalhada e compreensível.',grammar:'Imperativos, sequência e conectores de instrução',grammarNote:'Ordene ações com first, next, after that e finally; use imperativos para dar instruções claras.',vocab:'minecraft',content:'Tutorial de sobrevivência/construção com criador de fala clara; assista a algo já conhecido para prever o contexto.',resources:[['Minecraft Wiki — English','https://minecraft.wiki/'],['YouGlish','https://youglish.com/english']],activities:['Assista a um trecho conhecido sem legenda. Identifique objetivo e três ações.','Pause o tutorial e explique ao criador o próximo passo. Faça shadowing de uma instrução.','Escreva cinco instruções com imperativos e conectores para começar uma partida.','Roleplay: ajude um jogador novo a encontrar recursos e construir abrigo.','Ouça um vídeo de construção; responda antes do criador explicar por que escolheu um bloco.','Grave uma explicação curta de uma mecânica e peça à IA para corrigir clareza e tempos verbais.','Reassista sem texto. Escolha uma palavra do jogo e procure exemplos de pronúncia em contexto.']},
  {theme:'Tecnologia e vida digital',subtitle:'Resolva problemas digitais e descreva passos com precisão.',grammar:'Infinitivo / gerúndio em instruções e verbos comuns',grammarNote:'Pratique “try restarting”, “remember to save” e “avoid clicking”; note os verbos que pedem cada forma.',vocab:'technology',content:'Tutorial de configuração ou solução de problema; explique uma configuração que já usa.',resources:[['BBC Learning English','https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'],['Cambridge Dictionary','https://dictionary.cambridge.org/']],activities:['Ouça uma solução de problema técnico e anote os passos na ordem.','Explique como mudar uma configuração de idioma no dispositivo. Repita instruções em chorusing.','Compare verb + ing e verb + to com exemplos retirados do tutorial.','Roleplay: explique que seu dispositivo não conecta e responda perguntas de suporte.','Reouça o tutorial sem texto; tente prever cada etapa antes de ouvir.','Escreva instruções simples para resolver um problema digital e revise com IA.','Revise os verbos e faça uma nova gravação explicando o passo a passo.']},
  {theme:'Programação: explicar um bug',subtitle:'Conte o que esperava, o que aconteceu e como investigou.',grammar:'Passado simples × passado contínuo; sequência de eventos',grammarNote:'Use past simple para eventos concluídos e past continuous para o contexto: “I was testing… when it crashed.”',vocab:'programming',content:'Demonstração curta de depuração ou explicação de bug; escolha áudio com legendas inglesas.',resources:[['MDN Web Docs','https://developer.mozilla.org/en-US/'],['YouGlish','https://youglish.com/english']],activities:['Ouça uma explicação de bug e encontre resultado esperado versus resultado real.','Conte um problema simples de código. Faça shadowing de expressões para descrever o que aconteceu.','Reescreva uma sequência usando past simple e past continuous.','Simule uma conversa com colega: reproduza o bug e peça ajuda com contexto suficiente.','Assista a uma demonstração de debugging e pause antes da hipótese do programador.','Escreva um bug report curto em inglês; solicite correção que preserve detalhes técnicos.','Reconte o bug sem notas e reouça o trecho que foi mais difícil.']},
  {theme:'Opiniões e escolhas',subtitle:'Dê razões, compare alternativas e discorde com respeito.',grammar:'Conectores de contraste, causa e consequência',grammarNote:'Conecte ideias com although, however, because, so e as a result; evite encadear tudo com “and”.',vocab:'opinions',content:'Episódio curto de debate leve sobre tecnologia, jogos ou hábitos digitais.',resources:[['BBC Learning English — 6 Minute English','https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'],['British Council — B1 listening','https://learnenglish.britishcouncil.org/skills/listening/b1-listening']],activities:['Ouça duas opiniões e identifique em que ponto concordam ou discordam.','Dê sua opinião sobre uma atualização de jogo em 45 segundos, com uma razão e um exemplo.','Una frases curtas usando contraste, causa e consequência. Leia em voz alta.','Roleplay: compare duas ferramentas de programação e pergunte a opinião de outra pessoa.','Pause um vídeo antes da conclusão e diga o que você acha que o falante vai argumentar.','Escreva um parágrafo de opinião e peça à IA para apontar conectores repetidos ou confusos.','Reouça e resuma o argumento do falante com palavras diferentes.']},
  {theme:'Histórias e experiências',subtitle:'Conte algo que aconteceu e mantenha o ouvinte acompanhando.',grammar:'Tempos narrativos e discurso indireto básico',grammarNote:'Combine past simple, past continuous e past perfect quando necessário; relate fala com “She said that…”',vocab:'stories',content:'Relato pessoal curto ou história de jogo/desenvolvimento; observe marcadores de tempo e mudanças de cena.',resources:[['British Council — Audio series','https://learnenglish.britishcouncil.org/free-resources/general/audio-series'],['YouGlish','https://youglish.com/english']],activities:['Ouça uma história curta e identifique começo, problema e desfecho.','Conte uma experiência de jogo ou programação usando marcadores de tempo.','Reordene cinco eventos e escolha os tempos verbais para cada trecho.','Simule uma conversa contando algo inesperado; deixe a outra pessoa fazer perguntas.','Ouça de novo e pause em conectores temporais. Faça chorusing dessas frases.','Escreva uma história curta e peça feedback sobre clareza e sequência, não sobre estilo nativo.','Grave novamente sem ler e compare com sua primeira gravação.']},
  {theme:'Planos, metas e próximos passos',subtitle:'Fale sobre intenções e avalie seu progresso em inglês.',grammar:'Futuro: going to, will e present continuous',grammarNote:'Use going to para planos, will para decisões/previsões e present continuous para arranjos marcados.',vocab:'plans',content:'Entrevista sobre metas ou aprendizado; faça também sua revisão das 12 semanas com um áudio novo.',resources:[['CEFR descriptors — Council of Europe','https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors'],['British Council — B1 listening','https://learnenglish.britishcouncil.org/skills/listening/b1-listening']],activities:['Ouça alguém falar sobre metas. Identifique plano, motivo e próximo passo.','Explique em inglês como pretende continuar estudando e pratique conectores de sequência.','Compare will/going to/present continuous com situações reais do seu calendário.','Faça roleplay: converse com um colega sobre um plano conjunto e combine um horário.','Reouça um áudio da semana 1 e compare compreensão e confiança com hoje.','Escreva uma reflexão curta: o que ficou mais fácil, o que ainda trava e qual será a próxima meta.','Faça um resumo oral de 1 minuto e escolha materiais do próximo ciclo, calibrados ao seu nível.']}
];

const stateKey = 'englishQuestProgressV1';
let state = loadState();
state.lookups ||= {};
let activeVocabKey = null;
function loadState(){try{return JSON.parse(localStorage.getItem(stateKey))||{days:{},vocab:{}}}catch{return{days:{},vocab:{}}}}
function saveState(){localStorage.setItem(stateKey,JSON.stringify(state));updateProgress()}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function makeDayDescription(w,dayIndex){const f=weeklyFormats[dayIndex];return `<p><b>O que estudar:</b> ${escapeHtml(w.activities[dayIndex])}</p><p><b>Recurso:</b> ${escapeHtml(f.resource)}${w.resources?.[dayIndex%w.resources.length]?` · <a href="${w.resources[dayIndex%w.resources.length][1]}" target="_blank" rel="noreferrer">abrir recurso ↗</a>`:''}</p><p><b>Tempo:</b> 15 minutos · <b>Como praticar:</b> ${escapeHtml(f.task)}</p><p><b>Entrega do dia:</b> ${escapeHtml(f.output)}</p>`}
const verbHeads=new Set('wake get make take brush have leave commute run come cook do tidy go pick drop look spend manage need would eat book chop slice peel stir boil fry bake grill roast season taste smell order introduce catch hang keep follow bring change share ask listen show give turn cross set cancel explain breathe cough sneeze recover stay feel work hire apply hand deal figure carry put check wrap breed gather craft smelt grow light spawn despawn heal respawn mine dig build break activate deactivate place use open close hold right click enter update improve struggle find be practice review rehearse memorize remember forget recognize understand misunderstand pronounce spell plan schedule mix add serve order recommend invite meet move unpack assemble repair replace fix clean throw sort vacuum wash wipe pay rent sign host invite feed mark say ask enjoy avoid suggest persuade support challenge consider compare evaluate argue point call lead result make talk mention admit decide expect hope wonder promise describe complain claim measure estimate track complete continue pause adjust reflect maintain memorize recall summarize retell paraphrase'.split(' '));
const adjectiveWords=new Set('crowded quiet convenient nearby late early comfortable spacious tiny furnished unfurnished shared broken messy ripe fresh frozen canned spicy mild sweet sour bitter salty crispy soft tender overcooked undercooked thirsty hungry full vegetarian vegan healthy unwell sensitive severe dizzy tired exhausted stressed anxious relieved polite friendly awkward confident nervous curious supportive reliable available accessible opposite remote user-friendly secure compatible familiar clear realistic achievable consistent regular flexible focused reliable severe mild comfortable friendly confusing frozen secure'.split(' '));
const topicLabels={daily:'your daily routine',home:'your home',food:'food and meals',social:'meeting new people',directions:'getting around town',health:'health and wellbeing',work:'work',minecraft:'Minecraft',learning:'learning English',technology:'technology',programming:'programming',opinions:'choices and opinions',stories:'past experiences',plans:'future plans'};
const localMeanings={
 'wake up':'acordar; despertar','get dressed':'vestir-se; trocar de roupa','make the bed':'arrumar a cama','take a shower':'tomar banho','brush my teeth':'escovar os dentes','have breakfast':'tomar café da manhã','make coffee':'preparar café','leave home':'sair de casa','commute':'deslocar-se regularmente entre casa e trabalho; trajeto diário casa-trabalho','get to work':'chegar ao trabalho','take a break':'fazer uma pausa','have lunch':'almoçar','run an errand':'resolver uma tarefa fora de casa','come back':'voltar; retornar','cook dinner':'preparar o jantar','do the dishes':'lavar a louça','do the laundry':'lavar roupa','tidy up':'arrumar; organizar','take out the trash':'levar o lixo para fora','go to bed':'ir para a cama; ir dormir','weekday':'dia útil; dia de semana (segunda a sexta)','weekend':'fim de semana','morning':'manhã','afternoon':'tarde','evening':'começo da noite; período da noite','schedule':'agenda; cronograma; horário planejado','routine':'rotina','habit':'hábito','appointment':'compromisso marcado; consulta com hora marcada','reminder':'lembrete','alarm':'alarme; despertador','suburb':'subúrbio; bairro afastado do centro','neighborhood':'bairro; vizinhança','crosswalk':'faixa de pedestres','sidewalk':'calçada','traffic':'trânsito','bus stop':'ponto de ônibus','commute time':'tempo do deslocamento diário entre casa e trabalho','crowded':'lotado; cheio de gente','quiet':'silencioso; tranquilo','convenient':'prático; conveniente','nearby':'perto; nas proximidades','on time':'no horário; pontualmente','late':'atrasado; tarde','early':'cedo; adiantado','usually':'geralmente; normalmente','often':'frequentemente; muitas vezes','rarely':'raramente; quase nunca','sometimes':'às vezes','first':'primeiro; primeiro de tudo','then':'então; depois','afterwards':'depois; em seguida','before':'antes','while':'enquanto','until':'até; até que','because':'porque','although':'embora; apesar de','manage to':'conseguir fazer algo, especialmente com esforço','need to':'precisar fazer algo','have to':'ter que; precisar por obrigação','would rather':'preferir; preferiria','get ready':'preparar-se; ficar pronto','pick up':'buscar; pegar','drop off':'deixar alguém ou algo em um lugar','look for':'procurar','run out of':'ficar sem; acabar o estoque de','spend time':'passar tempo','in a hurry':'com pressa','at the moment':'no momento; agora','every other day':'dia sim, dia não; a cada dois dias','once a week':'uma vez por semana','take my time':'fazer sem pressa; levar o tempo necessário','make a plan':'fazer um plano; planejar'
};
const examplesByTerm={
 'because':['I stayed home because it was raining.','I’m learning English because I want to talk with more people.'],
 'although':['Although I was tired, I finished the lesson.','Although the bus was late, I arrived on time.'],
 'on time':['I arrived on time for the meeting.','The bus is usually on time in the morning.'],
 'early':['I got up early to catch the first bus.','We arrived early, so we had time for coffee.'],
 'late':['Sorry I’m late; the traffic was terrible.','I stayed up late to finish the project.'],
 'usually':['I usually listen to a podcast on my way to work.','We usually have dinner at home.'],
 'often':['I often call my family at the weekend.','This app often reminds me to take a break.'],
 'rarely':['I rarely eat out during the week.','She rarely misses her morning walk.'],
 'sometimes':['I sometimes study English during my lunch break.','We sometimes play Minecraft together in the evening.'],
 'morning':['I like to go for a walk in the morning.','I have my first cup of coffee every morning.'],
 'afternoon':['I have a meeting this afternoon.','The shop is quieter in the afternoon.'],
 'evening':['I usually cook dinner in the evening.','We watched a film together yesterday evening.'],
 'suburb':['My aunt lives in a quiet suburb outside the city.','It takes about twenty minutes to get from the suburb to downtown.'],
 'quiet':['The neighborhood is quiet early in the morning.','I’m looking for a quiet place to study.'],
 'convenient':['The bus stop near my house is really convenient.','Online banking is convenient when I’m busy.'],
 'nearby':['There’s a pharmacy nearby.','We found a nearby café and had lunch there.'],
 'in a hurry':['I was in a hurry, so I grabbed a banana and left.','Take your time; we’re not in a hurry.'],
 'at the moment':['I’m working on a new project at the moment.','She can’t talk at the moment; she’s in a meeting.'],
 'every other day':['I go for a walk every other day.','He practices the guitar every other day.'],
 'once a week':['We have an English conversation once a week.','I do the grocery shopping once a week.'],
 'take my time':['I like to take my time when I’m choosing a book.','There’s no rush; take your time.'],
 'be familiar with':['I’m familiar with that tool because I use it at work.','Are you familiar with the new settings?'],
 'be responsible for':['I’m responsible for updating the project every Friday.','Who is responsible for this task?'],
 'be into':['I’m really into survival games at the moment.','Are you into coding?'],
 'be keen on':['I’m keen on trying a new recipe this weekend.','He’s keen on learning English.'],
 'be available':['Are you available after work?','I’m available on Thursday morning.'],
 'be supposed to':['I’m supposed to meet my teammate at three.','Are we supposed to save the file before closing the app?'],
 'get together':['We get together with friends for dinner once a month.','Let’s get together this weekend and play Minecraft.'],
 'catch up':['I call my sister on Sundays to catch up.','We met for coffee and caught up on everything.'],
 'hang out':['We like to hang out at the park after work.','Do you want to hang out this weekend?'],
 'make friends':['It’s easier to make friends when you share an interest.','He made friends with his new coworkers.'],
 'keep in touch':['We moved to different cities, but we keep in touch.','Let’s keep in touch after the course ends.'],
 'get along':['I get along well with my neighbors.','Do you get along with your coworkers?'],
 'have in common':['My friend and I have a lot in common.','We both like games, so we have something in common.'],
 'small talk':['We made small talk while we waited for the meeting to start.','I usually make small talk about the weather.'],
 'take turns':['We take turns choosing what to watch.','The players took turns explaining their ideas.'],
 'follow up':['I’ll follow up with my coworker tomorrow.','She sent an email to follow up on the meeting.'],
 'bring up':['He brought up an important question during the meeting.','I’d like to bring up one small issue.'],
 'change the subject':['She changed the subject when the conversation became awkward.','Let’s change the subject and talk about the weekend.'],
 'give someone a hand':['Could you give me a hand with these bags?','My coworker gave me a hand with the presentation.'],
 'turn left':['Turn left at the traffic lights.','You’ll see the pharmacy after you turn left.'],
 'turn right':['Turn right at the next street.','We turned right and found the bus stop.'],
 'go straight':['Go straight for two blocks, then turn left.','If you go straight, you’ll see the station.'],
 'cross the street':['Wait for the light before you cross the street.','We crossed the street at the crosswalk.'],
 'get on':['I get on the bus near my house.','We got on the train just before it left.'],
 'get off':['I get off the bus at the next stop.','Let’s get off here and walk the rest of the way.'],
 'miss the bus':['I missed the bus, so I took a taxi.','Leave now or you’ll miss the bus.'],
 'catch a train':['We need to leave early to catch the train.','I caught a train to the city center.'],
 'feel under the weather':['I’m feeling under the weather, so I’m staying home.','She felt under the weather after the long trip.'],
 'make an appointment':['I need to make an appointment with the dentist.','Can I make an appointment for Friday morning?'],
 'take medicine':['Take this medicine with water after you eat.','I take my medicine every morning.'],
 'stay hydrated':['Remember to stay hydrated when it’s hot outside.','I keep a bottle of water nearby to stay hydrated.'],
 'meet a deadline':['We worked together to meet the deadline.','I need to finish this today to meet the deadline.'],
 'make a decision':['We need to make a decision before Friday.','It took me a while to make a decision.'],
 'solve a problem':['We worked together to solve the problem.','This update should solve the connection problem.'],
 'come up with an idea':['She came up with a great idea for the project.','Let’s come up with a simpler solution.'],
 'take responsibility':['He took responsibility for the mistake.','I’m ready to take responsibility for this task.'],
 'redstone circuit':['This redstone circuit opens the door automatically.','I built a simple redstone circuit to turn on the lights.'],
 'build a shelter':['We built a shelter before nightfall.','You should build a shelter near your spawn point.'],
 'gather resources':['We need to gather resources before exploring the cave.','I gathered resources to build a bigger base.'],
 'craft an item':['You need three planks to craft this item.','I crafted a shield before entering the Nether.'],
 'take damage':['You take damage when you fall from a great height.','The player took damage from the lava.'],
 'fix a bug':['I fixed a bug in the settings menu.','Can you help me fix this bug?'],
 'write code':['I write code in the morning when it’s quiet.','She wrote code to automate the task.'],
 'run a script':['I ran the script and checked the output.','You can run the script from the terminal.'],
 'set up a project':['I set up a project for the new feature.','We need to set up the project before we start coding.'],
 'log in':['I log in to my account with my email address.','You need to log in before you can change the settings.'],
 'sign in':['Please sign in to continue.','I signed in on my phone, but not on my laptop.'],
 'while':['I listened to a podcast while I cooked dinner.','She checked the map while we waited for the bus.'],
 'until':['I studied until 8 p.m.','We waited until the rain stopped.'],
 'first':['First, I check my messages; then I make coffee.','First, open the settings and choose English.'],
 'then':['I made breakfast, then I got ready for work.','Save the file, then restart the app.'],
 'afterwards':['We had dinner and went for a walk afterwards.','I finished the meeting and wrote a short summary afterwards.'],
 'before':['I check my schedule before I leave home.','Wash your hands before you start cooking.'],
 'actually':['Actually, I’ve already watched that video.','I thought the shop was closed, but it’s actually open.'],
 'by the way':['By the way, are you free this weekend?','I finished the update. By the way, I found one small bug.'],
 'to be honest':['To be honest, I prefer studying in the morning.','To be honest, that redstone design is a little complicated.'],
 'what do you think?':['I showed my friend the new build and asked, “What do you think?”','We tried the new restaurant. What do you think?'],
 'could you repeat that?':['Sorry, could you repeat that? I didn’t catch the last part.','Could you repeat that more slowly, please?'],
 'i didn’t catch that':['I’m sorry, I didn’t catch that. Could you say it again?','The connection was bad, so I didn’t catch that.'],
 'i’m not sure about that':['I’m not sure about that. Let’s check the instructions first.','I’m not sure about that idea, but I’d like to hear more.'],
 'i couldn’t agree more':['“We should test the update first.” “I couldn’t agree more.”','I couldn’t agree more; clear instructions save everyone time.'],
 'it depends':['“Can you join us?” “It depends on when I finish work.”','It depends on the weather, so let’s decide tomorrow.'],
 'wake up':['I usually wake up at seven on weekdays.','I woke up early because I had an appointment.'],
 'get to work':['I get to work before nine most days.','We got to work late because of the traffic.'],
 'take a break':['I take a short break after lunch.','Let’s take a break and get some water.'],
 'have lunch':['I usually have lunch with my coworkers.','We had lunch at a small café near the office.'],
 'run an errand':['I need to run an errand after work.','She ran a few errands before going home.'],
 'come back':['I’ll come back home after the meeting.','What time did you come back yesterday?'],
 'cook dinner':['I cook dinner at home most evenings.','We cooked dinner together last night.'],
 'do the dishes':['I do the dishes while my partner dries them.','Could you do the dishes after dinner?'],
 'do the laundry':['I do the laundry on Saturday mornings.','I need to do the laundry before my trip.'],
 'tidy up':['I tidy up my desk before I start work.','Let’s tidy up the kitchen after dinner.'],
 'take out the trash':['I take out the trash every evening.','Could you take out the trash before you leave?'],
 'go to bed':['I go to bed around eleven.','She went to bed early because she was tired.'],
 'get dressed':['I get dressed before I make breakfast.','He got dressed quickly and left the house.'],
 'make the bed':['I make the bed every morning.','She made the bed before the guests arrived.'],
 'take a shower':['I usually take a shower after my workout.','I took a quick shower before work.'],
 'brush my teeth':['I brush my teeth before I go to bed.','He brushed his teeth after breakfast.'],
 'have breakfast':['I have breakfast at home before work.','We had breakfast together on Sunday.'],
 'make coffee':['I make coffee as soon as I get up.','Would you like me to make coffee?'],
 'leave home':['I leave home at eight on weekdays.','She left home early to avoid traffic.'],
 'commute':['I commute by bus, so I listen to podcasts on the way.','His commute takes about thirty minutes.'],
 'get to work':['I get to work before nine most days.','We got to work late because of the traffic.'],
 'take a break':['I take a short break after lunch.','Let’s take a break and get some water.'],
 'have lunch':['I usually have lunch with my coworkers.','We had lunch at a small café near the office.'],
 'run an errand':['I need to run an errand after work.','She ran a few errands before going home.'],
 'come back':['I’ll come back home after the meeting.','What time did you come back yesterday?'],
 'cook dinner':['I cook dinner at home most evenings.','We cooked dinner together last night.'],
 'do the dishes':['I do the dishes while my partner dries them.','Could you do the dishes after dinner?'],
 'do the laundry':['I do the laundry on Saturday mornings.','I need to do the laundry before my trip.'],
 'tidy up':['I tidy up my desk before I start work.','Let’s tidy up the kitchen after dinner.'],
 'take out the trash':['I take out the trash every evening.','Could you take out the trash before you leave?'],
 'go to bed':['I go to bed around eleven.','She went to bed early because she was tired.'],
 'pick up':['I’ll pick up my friend at the station.','Can you pick up some milk on your way home?'],
 'drop off':['I drop off my son at school on my way to work.','Could you drop off this package for me?'],
 'look for':['I’m looking for my keys. Have you seen them?','We looked for a quiet café near the station.'],
 'run out of':['We ran out of coffee, so I added it to the shopping list.','My phone ran out of battery on the way home.'],
 'spend time':['I like to spend time with my friends at the weekend.','She spends a lot of time learning English.'],
 'need to':['I need to leave in ten minutes.','We need to check the address before we go.'],
 'have to':['I have to finish this task before lunch.','Do we have to book a table?'],
 'would rather':['I’d rather stay home tonight and watch a film.','Would you rather take the bus or walk?'],
 'get ready':['I get ready for work while the coffee is brewing.','We need to get ready before the taxi arrives.'],
 'weekday':['I usually get up early on weekdays.','The café is quieter on weekdays than at the weekend.'],
 'weekend':['What are you doing this weekend?','I usually visit my family at the weekend.'],
 'schedule':['I check my schedule every morning.','Could we move the meeting to a different time on the schedule?'],
 'routine':['A short morning routine helps me start the day calmly.','My routine changes when I work from home.'],
 'habit':['Reading before bed is a good habit.','I’m trying to build the habit of speaking English every day.'],
 'appointment':['I have a dentist appointment at three.','Could we reschedule my appointment for Friday?'],
 'reminder':['I set a reminder on my phone to take a break.','Thanks for the reminder; I almost forgot the meeting.'],
 'alarm':['My alarm goes off at seven every morning.','I set an alarm so I don’t miss the bus.'],
 'neighborhood':['There’s a good bakery in my neighborhood.','Our neighborhood is quiet at night.'],
 'bus stop':['The bus stop is across from the pharmacy.','I waited at the bus stop for ten minutes.'],
 'traffic':['There was a lot of traffic on my way to work.','We left early to avoid the traffic.'],
 'crosswalk':['Please use the crosswalk to cross the busy street.','The driver stopped to let us use the crosswalk.'],
 'sidewalk':['We walked along the sidewalk to the station.','The sidewalk is narrow near the construction site.'],
 'commute time':['I use my commute time to listen to English.','My commute time is shorter when I take the train.'],
 'in a hurry':['I was in a hurry, so I grabbed a banana and left.','Take your time; we’re not in a hurry.'],
 'at the moment':['I’m working on a new project at the moment.','She can’t talk at the moment; she’s in a meeting.'],
 'every other day':['I go for a walk every other day.','He practices the guitar every other day.'],
 'once a week':['We have an English conversation once a week.','I do the grocery shopping once a week.'],
 'take my time':['I like to take my time when I’m choosing a book.','There’s no rush; take your time.'],
 'make a plan':['Let’s make a plan for the weekend.','I made a plan to study English for fifteen minutes a day.']
};
function makeUsageExamples(term,group){if(examplesByTerm[term.toLowerCase()])return examplesByTerm[term.toLowerCase()];const topic=topicLabels[group]||'everyday life';if(term.includes('?')||/^(I |I’m |I’ve |I’ll |That |Could |Would |How |What |Where |Which |It )/i.test(term))return [`In a real conversation about ${topic}, you could say: “${term}.”`,`I used “${term}” when I was talking with a friend about ${topic}.`];if(adjectiveWords.has(term.toLowerCase())){const noun={home:'apartment',food:'meal',social:'conversation',directions:'street',health:'feeling',work:'schedule',minecraft:'build',technology:'device',programming:'solution',opinions:'choice',stories:'experience',plans:'goal',learning:'practice'}[group]||'day';return [`My ${noun} is ${term} today.`,`The place felt ${term}, so we decided to stay a little longer.`]}const first=term.split(/\s+/)[0].toLowerCase();if(verbHeads.has(first)){const endings={'pick up':'my friend at the station','drop off':'my friend near home','look for':'my keys','look up':'the word in a dictionary','run out of':'coffee','spend time':'with my friends','manage to':'finish the task','need to':'take a short break','have to':'leave soon','would rather':'stay home tonight','follow up':'with my coworker','ask for':'help','apply for':'the position','be responsible for':'the project','check in with':'my teammate','bring up':'the issue','come up with':'a better idea','figure out':'the answer','deal with':'the problem','carry out':'the plan','put off':'the meeting','set up':'my account','turn on':'the device','turn off':'the notifications','get used to':'the new routine','take care of':'the details','keep track of':'my progress','look after':'the kids','pick up groceries':'some groceries','make time for':'my English practice','set aside time':'my study session'};const tail=endings[term.toLowerCase()]||'';if(term.toLowerCase()==='would rather')return ['I’d rather stay home tonight and watch a film.','Would you rather take the bus or walk?'];if(term.toLowerCase()==='used to')return ['I used to walk to work when I lived nearby.','She used to play Minecraft with her brother.'];if(term.toLowerCase()==='get used to')return ['I’m getting used to my new schedule.','It takes time to get used to speaking English every day.'];if(term.toLowerCase()==='manage to')return ['I managed to finish the report before lunch.','Did you manage to find the right bus stop?'];if(term.toLowerCase()==='need to')return ['I need to leave in ten minutes.','We need to check the address before we go.'];if(term.toLowerCase()==='have to')return ['I have to finish this task before lunch.','Do we have to book a table?'];const phrase=tail?`${term} ${tail}`:term;return [`I usually ${phrase} as part of my ${topic}.`,`I sometimes ${phrase} when I have a little free time.`]}return [`I talked about the ${term} with a friend this week.`,`The ${term} came up while we were talking about ${topic}.`]}
async function translateVocab(term){const localMeaning=localMeanings[term.toLowerCase()];if(localMeaning)return localMeaning;if(state.lookups[term])return state.lookups[term];const url=new URL('https://api.mymemory.translated.net/get');url.searchParams.set('q',term);url.searchParams.set('langpair','en|pt-BR');const response=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error('translation unavailable');const data=await response.json();const value=data?.responseData?.translatedText;if(data?.responseStatus!==200||!value||value.toLowerCase().includes('no query specified'))throw new Error('translation unavailable');state.lookups[term]=value;saveState();return value}
async function openVocabCard(button,term,key,group){activeVocabKey=key;const dialog=document.getElementById('vocab-dialog');document.getElementById('vocab-dialog-title').textContent=term;const translation=document.getElementById('vocab-translation');const localMeaning=localMeanings[term.toLowerCase()];translation.textContent=state.lookups[term]||localMeaning||'Buscando tradução…';document.getElementById('vocab-meaning-note').textContent=localMeaning?'Significado contextual deste roteiro; use os exemplos para observar a expressão em situação.':state.lookups[term]?'Tradução automática; considere o contexto da semana para confirmar o sentido.':'Tradução automática para orientar; o contexto ajuda a escolher o sentido.';document.getElementById('vocab-youglish').href=`https://youglish.com/pronounce/${encodeURIComponent(term)}/english`;document.getElementById('vocab-cambridge').href=`https://dictionary.cambridge.org/dictionary/english/${encodeURIComponent(term)}`;document.getElementById('vocab-example-list').innerHTML=makeUsageExamples(term,group).map((example,i)=>`<article class="vocab-example"><span>${i+1}</span><p>${escapeHtml(example)}</p></article>`).join('');const complete=document.getElementById('vocab-complete');complete.textContent=state.vocab[key]?'Concluído ✓ · desfazer':'Concluir';dialog.showModal();if(!state.lookups[term]&&!localMeaning){try{const meaning=await translateVocab(term);if(activeVocabKey===key&&dialog.open){translation.textContent=meaning;document.getElementById('vocab-meaning-note').textContent='Tradução automática; considere o contexto da semana para confirmar o sentido.'}}catch{if(activeVocabKey===key&&dialog.open){translation.textContent='Tradução indisponível agora. Você ainda pode ver os exemplos e consultar o dicionário.';document.getElementById('vocab-meaning-note').textContent='Verifique a conexão ou abra a definição no Cambridge Dictionary.'}}}}
function render(){const root=document.getElementById('weeks-container');root.innerHTML=weeks.map((w,i)=>{const n=i+1;const vocab=vocabSets[w.vocab];return `<article class="week-card ${i===0?'open':''}" data-week="${i}"><button class="week-summary" type="button" aria-expanded="${i===0?'true':'false'}"><span class="week-num">W${String(n).padStart(2,'0')}</span><span><span class="week-title">${escapeHtml(w.theme)}</span><span class="week-subtitle">${escapeHtml(w.subtitle)}</span></span><span class="week-chip">${escapeHtml(w.grammar)}</span><span class="week-chevron">⌄</span></button><div class="week-details"><div class="week-overview"><div class="detail-box"><h4>Foco gramatical</h4><p><b>${escapeHtml(w.grammar)}</b><br>${escapeHtml(w.grammarNote)}</p></div><div class="detail-box"><h4>Conteúdo da semana</h4><p>${escapeHtml(w.content)}</p></div></div><div class="vocab-header"><h4>Vocabulário essencial</h4><span class="vocab-count" data-vocab-count="${i}"></span></div><div class="vocab-list">${vocab.map((term,j)=>{const key=`${i}-${j}`;return `<button class="vocab-item ${state.vocab[key]?'learned':''}" type="button" data-vocab="${key}" aria-pressed="${!!state.vocab[key]}" title="Ver significado e exemplos">${escapeHtml(term)}</button>`}).join('')}</div><div class="week-resources"><b>Materiais e recursos</b>${w.resources.map(r=>`<a href="${r[1]}" target="_blank" rel="noreferrer">${escapeHtml(r[0])} ↗</a>`).join('')}<a href="https://www.bbc.co.uk/learningenglish/english/features/6-minute-english" target="_blank" rel="noreferrer">BBC 6 Minute English ↗</a></div><div class="days-heading">Plano diário · 15 min por sessão</div><div class="day-list">${dayNames.map((day,d)=>{const key=`${i}-${d}`;return `<div class="day-item"><div class="day-trigger"><input class="day-check" type="checkbox" data-day="${key}" aria-label="Marcar ${day} da semana ${n} como concluído" ${state.days[key]?'checked':''}><button type="button" class="day-trigger-main"><span class="day-name">${day}</span><span class="day-focus">${escapeHtml(weeklyFormats[d].name)}</span><span class="day-time">15 min</span><span class="day-toggle">⌄</span></button></div><div class="day-detail">${makeDayDescription(w,d)}</div></div>`}).join('')}</div></div></article>`}).join('');
 root.querySelectorAll('.week-summary').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.week-card');const open=!card.classList.contains('open');card.classList.toggle('open',open);btn.setAttribute('aria-expanded',String(open))}));
 root.querySelectorAll('.day-trigger-main').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.day-item').classList.toggle('expanded')));
 root.querySelectorAll('.day-check').forEach(box=>box.addEventListener('change',()=>{state.days[box.dataset.day]=box.checked;saveState()}));
 root.querySelectorAll('.vocab-item').forEach(btn=>btn.addEventListener('click',()=>{const [weekIndex,termIndex]=btn.dataset.vocab.split('-').map(Number);openVocabCard(btn,vocabSets[weeks[weekIndex].vocab][termIndex],btn.dataset.vocab,weeks[weekIndex].vocab)}));updateProgress()}
function updateProgress(){const completed=Object.values(state.days).filter(Boolean).length;const pct=Math.round(completed/(weeks.length*7)*100);document.getElementById('overall-percent').textContent=`${pct}%`;document.getElementById('overall-bar').style.width=`${pct}%`;document.getElementById('completed-count').textContent=`${completed} de ${weeks.length*7} sessões`;document.querySelectorAll('.vocab-count').forEach(label=>{const weekIndex=Number(label.dataset.vocabCount);const total=vocabSets[weeks[weekIndex].vocab].length;const learned=Array.from({length:total},(_,i)=>state.vocab[`${weekIndex}-${i}`]).filter(Boolean).length;label.textContent=`${learned}/${total} concluídas · clique para ver significado e exemplos`});let current=weeks.length;for(let w=0;w<weeks.length;w++){let weekDone=true;for(let d=0;d<7;d++)if(!state.days[`${w}-${d}`])weekDone=false;if(!weekDone){current=w+1;break}}document.getElementById('week-count').textContent=`Semana ${current} de ${weeks.length}`}
let toastTimer;function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
document.getElementById('export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'english-quest',version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-quest-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup baixado. Guarde o arquivo em local seguro.')});
document.getElementById('import-file').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const imported=data.state||data;if(!imported.days||!imported.vocab)throw new Error('invalid');state={days:imported.days,vocab:imported.vocab,lookups:imported.lookups||{}};saveState();render();toast('Progresso importado neste navegador.')}catch{toast('Arquivo inválido. Escolha um backup English Quest.')}e.target.value=''});
document.getElementById('vocab-close').addEventListener('click',()=>document.getElementById('vocab-dialog').close());
document.getElementById('vocab-complete').addEventListener('click',()=>{if(!activeVocabKey)return;state.vocab[activeVocabKey]=!state.vocab[activeVocabKey];const button=document.querySelector(`.vocab-item[data-vocab="${activeVocabKey}"]`);if(button){button.classList.toggle('learned',state.vocab[activeVocabKey]);button.setAttribute('aria-pressed',String(state.vocab[activeVocabKey]))}saveState();document.getElementById('vocab-dialog').close()});
document.getElementById('vocab-dialog').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close()});
render();
